<?php
/*
* This file is part of phpMorphy project
*
* Copyright (c) 2007-2012 Kamaev Vladimir <heromantor@users.sourceforge.net>
*
*     This library is free software; you can redistribute it and/or
* modify it under the terms of the GNU Lesser General Public
* License as published by the Free Software Foundation; either
* version 2 of the License, or (at your option) any later version.
*
*     This library is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* Lesser General Public License for more details.
*
*     You should have received a copy of the GNU Lesser General Public
* License along with this library; if not, write to the
* Free Software Foundation, Inc., 59 Temple Place - Suite 330,
* Boston, MA 02111-1307, USA.
*/
 echo '<' . '?' . 'php' ?> 
declare(encoding = 'utf-8');
// This file is autogenerated at <?php echo date('r') ?>, don`t change it!

<?php foreach($all_constants as $consts): ?>
// consts for <?php echo $lang = $consts->getLanguage() ?> language
// part of speech
<?php foreach($consts->getPosesMap() as $item): ?>
/**
 * <?php echo $helper->posConstName($consts, $item['const']), ' ', '"', $item['name'], '" part of speech'; ?>
 */
define('<?php echo $helper->posConstName($consts, $item['const']) ?>', <?php echo $item['id'] ?>);
<?php endforeach; ?>
    
// grammems
<?php foreach($consts->getGrammemsMap() as $item): ?>
/**
 * <?php echo $helper->grammemConstName($consts, $item['const']), ' ', '"', $item['name'], '" grammem'; ?>
 */
define('<?php echo $helper->grammemConstName($consts, $item['const']) ?>', <?php echo $item['id'] ?>);
<?php endforeach; ?>

// meta grammems
<?php foreach($consts->getMetaGrammemsMap() as $item): ?>
function <?php echo $helper->grammemConstName($consts, $item['const']) ?>() { return <?php echo $helper->metaGrammemConstValue($consts, $item['consts_list']) ?>; }
<?php endforeach; ?>

<?php endforeach; ?>
