// This file is autogenerated at <?php echo date('r') ?>, don`t change it!
#ifndef _MORPHY_LIBMORPHY_GRAMTAB_HPP
#define _MORPHY_LIBMORPHY_GRAMTAB_HPP

#include <morphy/libmorphy/libmorphy_config.h>
#include "morph_data.hpp"

namespace morphy { namespace libmorphy { namespace GramTab {

using morphy::libmorphy::MorphData::BitString;

<?php foreach($helpers as $helper): ?>
namespace <?php echo $lang = mb_convert_case($helper->getLanguage(), MB_CASE_TITLE, 'utf-8'); ?> {
    namespace PartOfSpeech {
<?php foreach($helper->getPosesMap() as $item): ?>
        LIBMORPHY_API extern const uint16_t <?php echo $item['const'] ?>; // name => <?php echo $item['name']; ?> 
<?php endforeach; ?>
    } // namespace PartOfSpeech {
    
    namespace Grammem {
<?php foreach($helper->getGrammemsMap() as $item): ?>
        LIBMORPHY_API extern const BitString <?php echo $item['const'] ?>; // name => <?php echo $item['name']; ?> 
<?php endforeach; ?>

<?php foreach($helper->getMetaGrammemsMap() as $item): ?>
        LIBMORPHY_API extern const BitString <?php echo $item['const'] ?>;
<?php endforeach; ?>
    } // namespace Grammem {

    namespace g = Grammem;
    namespace p = PartOfSpeech;
} // namespace <?php echo $lang ?> 

<?php endforeach; ?>

} } } // namespace morphy { namespace libmorphy { namespace GramTab {
#endif _MORPHY_LIBMORPHY_GRAMTAB_HPP
