// This file is autogenerated at <?php echo date('r') ?>, don`t change it!
#include "<?php echo $header_file ?>"

namespace morphy { namespace libmorphy { namespace GramTab {

static BitString init_bitstring(size_t shift) {
     BitString bs;
     bs.set(shift, 1);
     return bs;
};

<?php foreach($helpers as $helper): ?>
namespace <?php echo $lang = mb_convert_case($helper->getLanguage(), MB_CASE_TITLE, 'utf-8'); ?> {
    namespace PartOfSpeech {
<?php foreach($helper->getPosesMap() as $item): ?>
        const uint16_t <?php echo $item['const'] ?> = <?php echo $item['id'] ?>;
<?php endforeach; ?>
    } // namespace PartOfSpeech {
    
    namespace Grammem {
<?php foreach($helper->getGrammemsMap() as $item): ?>
        const BitString <?php echo $item['const'] ?> = init_bitstring(<?php echo $item['shift'] ?>);
<?php endforeach; ?>

<?php foreach($helper->getMetaGrammemsMap() as $item): ?>
        const BitString <?php echo $item['const'] ?> = <?php echo implode(' | ', $item['consts_list']); ?>;
<?php endforeach; ?>
    } // namespace Grammem {
} // namespace <?php echo $lang ?> 

<?php endforeach; ?>
    
} } } // namespace morphy { namespace libmorphy { namespace GramTab {
